### ISSUE TITLE
Replace RSS button

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/NeatlineFeatures#2]
Replace the RSS button with add image

**Comment by jeremyboggs** [comment]
Where exactly is this displayed?

**Comment by davidmcclure** [comment]
Jeremy, these tickets were pulled over automatically with the svn migration back over the summer, so I didn't actually create this ticket (looks like GH just assigns authorship to the account doing the API push to all the tickets).

As far as I know, this version of Features is not at all functional, and I don't expect that we'll want to use any of the code.

**Comment by jeremyboggs** [comment]
Sounds good. I'll close this issue, then.
