### ISSUE TITLE
Set the viewport

### ISSUE THREAD

**Issue by erochest** [scholarslab/NeatlineFeatures#20]
Allow the user to set and save the viewport of the coverage field.

**Comment by erochest** [comment]
I'm not sure what the best way to handle this would be. The map could implicitly save and restore the last view while in edit mode. Or I could add a save view / restore view button combination that would save the current view or restore the view to the last one saved.

**Comment by davidmcclure** [comment]
NL does this by making it possible to save a default map bounds / zoom, either at the level fo the exhibit or for a specific item. See the default_map_bounds/default_map_zoom cols on the exhibits table, and the map_bounds/map_zoom cols on the data records table - https://github.com/scholarslab/Neatline/blob/dev/NeatlinePlugin.php#L92. You can use getExtentForSave() and getZoomForSave() on the map widget to get the values - https://github.com/scholarslab/Neatline/blob/dev/views/shared/javascripts/neatline_map.js#L695.

I think this is an important feature. After I implemented it in NL, I realized that it has the added benefit of making it possible to just set a geospatial _focus_ for an item, even if there isn't any added vector geometry. For example, maybe you just want to focus the map on some specific town, but don't necessarily need or want to draw anything on or around the focus point.

**Comment by erochest** [comment]
I need to change the data format to GML and use namespaces segment out the elements that store the viewport.

**Comment by erochest** [comment]
Per #28, the viewport will go into a separate table.

**Comment by erochest** [comment]
Also, if we don't automatically save the viewport, it may be a good idea to display the currently saved viewport using a light right rectangle or something.

**Comment by erochest** [comment]
Because this involves saving the map state, this depends on #28.
