### ISSUE TITLE
Break all data fields out of the hidden text field into their own hidden fields

### ISSUE THREAD

**Issue by erochest** [scholarslab/NeatlineFeatures#38]
Currently, there's a visible field for free-text, the map, and a hidden field that contains the free text plus several other fields (WKT, zoom setting, and center). As we add more fields (e.g., base layer for #29), this is going to get harder and harder to maintain.

Instead, there should be an array of hidden fields, one for each field, and they should be stored in the `neatline_features` table, which currently only stores the `is_map` setting.

**Comment by waynegraham** [comment]
It may be worth looking at KML (http://code.google.com/apis/kml/documentation/topicsinkml.html) which has definitions for zoom, center, etc. OpenLayers can output this almost as easily as wkt (http://dev.openlayers.org/apidocs/files/OpenLayers/Format/KML-js.html)
