### ISSUE TITLE
Make it possible to pan the map in public item show views

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/NeatlineFeatures#40]
In the public item show view, the map control defaults to a box selection tool that lets you drag out an area on the map. When I hit the page, thought, I wanted to be able to pan the map, not select features.

It could be useful to add a simple control that would let you toggle back and forth. I suspect, though, that in most cases people will want / expect to be able to pan, since that's the default pattern in Google Maps, etc.

**Comment by erochest** [comment]
This is a duplicate of #35.
