### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by EvanPHamilton** [scholarslab/NeatlineFeatures#87]
I recently tried to update from NeatlineFeatures 2.0.1 to 2.0.4. I was able to unzip the file, but when I went to configure the plugin in my Omeka Admin Page it is saying that this is not a valid plugin. Wondering if anyone might be able to explain why.

**Comment by EvanPHamilton** [comment]
Redacted. Problem solved.

**Comment by erochest** [comment]
:)
